import { makePreset, question } from '../builders';

export default makePreset(
  'ancient-history',
  'Ancient History',
  'Civilizations',
  'Empires, rulers, inventions, and old-world drama.',
  [
    question('Which river was central to Ancient Egyptian civilization?', ['Tigris', 'Nile', 'Indus', 'Danube'], 'B'),
    question('Who was the first emperor of a unified China?', ['Qin Shi Huang', 'Han Wudi', 'Kublai Khan', 'Sun Tzu'], 'A'),
    question('Which city-state is famous for its military society?', ['Athens', 'Corinth', 'Sparta', 'Thebes'], 'C'),
    question('The Code of Hammurabi comes from which civilization?', ['Babylonian', 'Roman', 'Mayan', 'Persian'], 'A'),
    question('Which empire built Persepolis?', ['Assyrian', 'Persian', 'Mauryan', 'Byzantine'], 'B'),
    question('Who was the Macedonian king who conquered much of Persia?', ['Philip II', 'Alexander the Great', 'Leonidas', 'Ptolemy'], 'B'),
    question('Which ancient people built Machu Picchu?', ['Aztec', 'Maya', 'Inca', 'Olmec'], 'C'),
    question('What writing system used wedge-shaped marks on clay tablets?', ['Hieroglyphics', 'Cuneiform', 'Sanskrit', 'Linear B'], 'B'),
    question('Which Roman leader was assassinated on the Ides of March?', ['Augustus', 'Julius Caesar', 'Nero', 'Trajan'], 'B'),
    question('Which ancient Indian emperor promoted Buddhism after the Kalinga War?', ['Ashoka', 'Chandragupta I', 'Harsha', 'Akbar'], 'A'),
    question('The Parthenon was dedicated to which goddess?', ['Hera', 'Athena', 'Artemis', 'Aphrodite'], 'B'),
    question('Which sea connected many ancient Mediterranean trade routes?', ['Baltic Sea', 'Red Sea', 'Mediterranean Sea', 'Caspian Sea'], 'C'),
    question('Who is known for the military treatise The Art of War?', ['Confucius', 'Sun Tzu', 'Laozi', 'Mencius'], 'B'),
    question('Which civilization developed a famous early democracy?', ['Athens', 'Carthage', 'Babylon', 'Memphis'], 'A'),
    question('The Rosetta Stone helped decode which script?', ['Runes', 'Hieroglyphics', 'Cuneiform', 'Phoenician'], 'B'),
    question('Which empire was ruled from the city of Tenochtitlan?', ['Inca', 'Aztec', 'Minoan', 'Hittite'], 'B'),
    question('Which Roman structure hosted gladiator games?', ['Pantheon', 'Colosseum', 'Forum', 'Aqueduct'], 'B'),
    question('Which ancient trade route linked China with the Mediterranean world?', ['Amber Road', 'Silk Road', 'Royal Road', 'Tea Road'], 'B'),
    question('Which civilization used oracle bones for divination?', ['Shang China', 'Gupta India', 'Old Kingdom Egypt', 'Classical Greece'], 'A'),
    question('Which city was buried by the eruption of Mount Vesuvius in 79 CE?', ['Pompeii', 'Troy', 'Knossos', 'Ur'], 'A'),
    question('Which ruler is associated with the Great Pyramid at Giza?', ['Tutankhamun', 'Khufu', 'Ramses II', 'Akhenaten'], 'B'),
    question('Which ancient civilization built ziggurats in Mesopotamia?', ['Vikings', 'Celts', 'Sumerians', 'Etruscans'], 'C'),
    question('The Punic Wars were fought mainly between Rome and which rival city?', ['Athens', 'Alexandria', 'Babylon', 'Carthage'], 'D'),
    question('Which Greek historian is often called the father of history?', ['Herodotus', 'Socrates', 'Aristotle', 'Homer'], 'A'),
    question('Which ancient empire used satraps to govern its provinces?', ['Persian Empire', 'Minoan Civilization', 'Aztec Empire', 'Roman Republic'], 'A'),
    question('Which city was the legendary home of King Priam in the Iliad?', ['Thebes', 'Troy', 'Knossos', 'Corinth'], 'B'),
    question('What was the main language of the Roman Empire in the west?', ['Greek', 'Aramaic', 'Latin', 'Phoenician'], 'C'),
    question('Which queen was the last active ruler of Ptolemaic Egypt?', ['Hatshepsut', 'Nefertiti', 'Boudica', 'Cleopatra VII'], 'D'),
    question('Which ancient culture is strongly associated with the city of Knossos?', ['Minoan', 'Mycenaean', 'Etruscan', 'Phoenician'], 'A'),
    question('Which river valley civilization had major cities like Harappa and Mohenjo-daro?', ['Indus Valley', 'Nile Valley', 'Yellow River', 'Tigris Valley'], 'A'),
    question('Which Roman emperor made Christianity legally tolerated with the Edict of Milan?', ['Diocletian', 'Constantine', 'Nero', 'Commodus'], 'B'),
    question('Which ancient people are credited with spreading an alphabet around the Mediterranean?', ['Huns', 'Saxons', 'Phoenicians', 'Mongols'], 'C'),
    question('Which battle in 490 BCE saw Athens defeat a Persian invasion force?', ['Cannae', 'Actium', 'Gaugamela', 'Marathon'], 'D'),
    question('What was the name of the elite Persian royal road network?', ['Royal Road', 'Via Appia', 'Amber Road', 'Tin Road'], 'A'),
    question('Which Mauryan adviser is linked with the political treatise Arthashastra?', ['Chanakya', 'Kalidasa', 'Patanjali', 'Aryabhata'], 'A'),
    question('Which Egyptian pharaoh is famous for a nearly intact tomb discovered in 1922?', ['Djoser', 'Tutankhamun', 'Sneferu', 'Seti I'], 'B'),
    question('Which ancient empire was centered on Hattusa in Anatolia?', ['Assyrian', 'Akkadian', 'Hittite', 'Seleucid'], 'C'),
    question('Which Roman road is one of the earliest and most famous major roads of Rome?', ['Silk Road', 'King Road', 'Icknield Way', 'Appian Way'], 'D'),
    question('Which Chinese dynasty is known for the Terracotta Army?', ['Qin', 'Tang', 'Song', 'Ming'], 'A'),
    question('Which ancient Greek physician is associated with an oath for medical ethics?', ['Hippocrates', 'Galen', 'Euclid', 'Archimedes'], 'A'),
  ],
  1,
);
