import { makePreset, question } from '../builders';

export default makePreset(
  'games',
  'Games',
  'Play',
  'Consoles, classics, characters, and gaming lore.',
  [
    question('Which company created the Mario franchise?', ['Sega', 'Nintendo', 'Sony', 'Valve'], 'B'),
    question('In Minecraft, what material is needed to craft a Nether portal frame?', ['End Stone', 'Obsidian', 'Bedrock', 'Granite'], 'B'),
    question('Which game features the character Master Chief?', ['Halo', 'Doom', 'Destiny', 'Mass Effect'], 'A'),
    question('What is the main collectible creature type in Pokemon?', ['Digimon', 'Monsters', 'Pokemon', 'Yo-kai'], 'C'),
    question('Which battle royale game is known for building mechanics?', ['Apex Legends', 'PUBG', 'Fortnite', 'Warzone'], 'C'),
    question('In The Legend of Zelda, what is the hero usually named?', ['Link', 'Zelda', 'Ganon', 'Navi'], 'A'),
    question('Which game is famous for the phrase "The cake is a lie"?', ['Portal', 'Half-Life', 'BioShock', 'Control'], 'A'),
    question('Which studio created The Witcher 3?', ['Bethesda', 'CD Projekt Red', 'FromSoftware', 'BioWare'], 'B'),
    question('What genre is Stardew Valley best known as?', ['Farming sim', 'Racing', 'Fighting', 'Horror'], 'A'),
    question('Which game series includes Ryu and Chun-Li?', ['Tekken', 'Street Fighter', 'Mortal Kombat', 'Virtua Fighter'], 'B'),
    question('What color is Sonic the Hedgehog?', ['Red', 'Blue', 'Green', 'Yellow'], 'B'),
    question('Which game features the city of Rapture?', ['BioShock', 'Dishonored', 'Prey', 'Fallout'], 'A'),
    question('In Among Us, players try to find which hidden role?', ['Builder', 'Impostor', 'Merchant', 'Pilot'], 'B'),
    question('Which company makes the PlayStation console?', ['Microsoft', 'Sony', 'Nintendo', 'Atari'], 'B'),
    question('Which game series is known for catching monsters in Pokeballs?', ['Persona', 'Pokemon', 'Monster Hunter', 'Dragon Quest'], 'B'),
    question('Which indie game features a fallen child in the Underground?', ['Celeste', 'Hades', 'Undertale', 'Hollow Knight'], 'C'),
    question('Which game has creepers that explode?', ['Terraria', 'Minecraft', 'Roblox', 'Valheim'], 'B'),
    question('Which racing series uses blue shells?', ['Need for Speed', 'Forza', 'Mario Kart', 'Gran Turismo'], 'C'),
    question('Which game popularized the battle pass model at massive scale?', ['Fortnite', 'Tetris', 'Skyrim', 'Portal 2'], 'A'),
    question('Which game series features the Triforce?', ['Final Fantasy', 'Zelda', 'Kingdom Hearts', 'Metroid'], 'B'),
    question('Which 1993 shooter helped popularize first-person shooter games on PC?', ['Myst', 'Doom', 'Diablo', 'SimCity 2000'], 'B'),
    question('Which game series is set mainly in the post-apocalyptic wasteland of Vault-Tec vaults?', ['Far Cry', 'Fable', 'Fallout', 'Fire Emblem'], 'C'),
    question('Which studio developed Elden Ring?', ['Naughty Dog', 'Rare', 'Respawn Entertainment', 'FromSoftware'], 'D'),
    question('In Tetris, what is the four-line clear commonly called?', ['Tetris', 'Combo', 'Stack', 'Sweep'], 'A'),
    question('Which console introduced motion-focused Wii Remote controls?', ['Nintendo Wii', 'Xbox 360', 'PlayStation 2', 'Dreamcast'], 'A'),
    question('Which game features the silent protagonist Gordon Freeman?', ['Deus Ex', 'Half-Life', 'Quake', 'System Shock'], 'B'),
    question('Which series lets players build and manage a city as mayor?', ['Civilization', 'Age of Empires', 'SimCity', 'Command and Conquer'], 'C'),
    question('Which handheld console succeeded the Nintendo DS family?', ['Game Boy Color', 'PS Vita', 'Sega Nomad', 'Nintendo 3DS'], 'D'),
    question('Which game asks players to survive nights against animatronics?', ['Five Nights at Freddy\'s', 'Dead Space', 'Resident Evil', 'Silent Hill'], 'A'),
    question('Which Valve game is built around testing chambers and a portal gun?', ['Portal', 'Team Fortress 2', 'Left 4 Dead', 'Counter-Strike'], 'A'),
    question('Which game series uses the phrase "Finish Him" before a fatality?', ['Street Fighter', 'Mortal Kombat', 'Tekken', 'Soulcalibur'], 'B'),
    question('Which farming RPG begins when the player inherits a farm from their grandfather?', ['Animal Crossing', 'Harvestella', 'Stardew Valley', 'Rune Factory 5'], 'C'),
    question('Which character is the main mascot of the Kirby series?', ['Meta Knight', 'King Dedede', 'Waddle Dee', 'Kirby'], 'D'),
    question('Which puzzle game features companion cubes?', ['Portal', 'The Witness', 'Baba Is You', 'Fez'], 'A'),
    question('Which company created the Xbox console line?', ['Microsoft', 'Sony', 'Nintendo', 'Sega'], 'A'),
    question('Which game series follows assassins using genetic memories through the Animus?', ['Hitman', 'Assassin\'s Creed', 'Dishonored', 'Watch Dogs'], 'B'),
    question('Which online game is known for champions, lanes, and Summoner\'s Rift?', ['Dota Underlords', 'Valorant', 'League of Legends', 'Overwatch'], 'C'),
    question('Which game features a goose causing mischief in a quiet village?', ['Goat Simulator', 'Donut County', 'Octodad', 'Untitled Goose Game'], 'D'),
    question('Which space exploration game launched with procedurally generated planets?', ['No Man\'s Sky', 'Kerbal Space Program', 'Elite Beat Agents', 'Starbound'], 'A'),
    question('Which PlayStation series stars Kratos?', ['God of War', 'Uncharted', 'Ratchet and Clank', 'Jak and Daxter'], 'A'),
  ],
  2,
);
