import { makePreset, question } from '../builders';

export default makePreset(
  'geography',
  'Geography',
  'World',
  'Capitals, landmarks, rivers, mountains, and maps.',
  [
    question('What is the capital of Japan?', ['Kyoto', 'Tokyo', 'Osaka', 'Nagoya'], 'B'),
    question('Which continent is the Sahara Desert in?', ['Asia', 'Africa', 'Australia', 'South America'], 'B'),
    question('What is the longest river in the world by common school convention?', ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], 'B'),
    question('Which country has the city of Barcelona?', ['Portugal', 'Spain', 'Italy', 'France'], 'B'),
    question('Mount Everest lies in which mountain range?', ['Andes', 'Alps', 'Himalayas', 'Rockies'], 'C'),
    question('Which ocean is the largest?', ['Atlantic', 'Indian', 'Pacific', 'Arctic'], 'C'),
    question('What is the capital of Canada?', ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'], 'C'),
    question('Which country is shaped like a boot?', ['Greece', 'Italy', 'Chile', 'Norway'], 'B'),
    question('The Great Barrier Reef is near which country?', ['Brazil', 'Australia', 'India', 'Mexico'], 'B'),
    question('Which river flows through Paris?', ['Thames', 'Seine', 'Rhine', 'Danube'], 'B'),
    question('What is the capital of Egypt?', ['Cairo', 'Alexandria', 'Luxor', 'Giza'], 'A'),
    question('Which country has the most natural lakes?', ['Canada', 'India', 'Spain', 'Japan'], 'A'),
    question('Which U.S. state is known as the Sunshine State?', ['California', 'Florida', 'Texas', 'Arizona'], 'B'),
    question('Which desert covers much of Mongolia and northern China?', ['Gobi', 'Kalahari', 'Atacama', 'Mojave'], 'A'),
    question('Which city is home to the Colosseum?', ['Athens', 'Rome', 'Istanbul', 'Madrid'], 'B'),
    question('What is the capital of Brazil?', ['Rio de Janeiro', 'Sao Paulo', 'Brasilia', 'Salvador'], 'C'),
    question('Which sea separates Europe and Africa near Italy?', ['Caribbean Sea', 'Mediterranean Sea', 'Baltic Sea', 'Black Sea'], 'B'),
    question('Which country contains Machu Picchu?', ['Peru', 'Chile', 'Colombia', 'Bolivia'], 'A'),
    question('Which is the smallest continent?', ['Europe', 'Australia', 'Antarctica', 'South America'], 'B'),
    question('What is the capital of South Korea?', ['Busan', 'Seoul', 'Incheon', 'Daegu'], 'B'),
    question('Which country has the capital city Reykjavik?', ['Norway', 'Iceland', 'Finland', 'Denmark'], 'B'),
    question('Which mountain range runs along the western edge of South America?', ['Alps', 'Atlas', 'Andes', 'Urals'], 'C'),
    question('Which river flows through London?', ['Seine', 'Tiber', 'Vistula', 'Thames'], 'D'),
    question('Which country is both a continent and a nation?', ['Australia', 'Greenland', 'Madagascar', 'New Zealand'], 'A'),
    question('Which strait separates Morocco and Spain?', ['Strait of Gibraltar', 'Bering Strait', 'Bosporus', 'Malacca Strait'], 'A'),
    question('What is the capital of Kenya?', ['Mombasa', 'Nairobi', 'Kampala', 'Addis Ababa'], 'B'),
    question('Which country has the ancient city of Petra?', ['Egypt', 'Turkey', 'Jordan', 'Iran'], 'C'),
    question('Which is the largest island in the world?', ['Borneo', 'Madagascar', 'New Guinea', 'Greenland'], 'D'),
    question('Which lake is the deepest freshwater lake in the world?', ['Lake Baikal', 'Lake Superior', 'Lake Victoria', 'Lake Tanganyika'], 'A'),
    question('Which country has the city of Marrakech?', ['Morocco', 'Algeria', 'Tunisia', 'Lebanon'], 'A'),
    question('Which U.S. state contains Denali?', ['Colorado', 'Alaska', 'Washington', 'Montana'], 'B'),
    question('Which canal connects the Mediterranean Sea and the Red Sea?', ['Panama Canal', 'Grand Canal', 'Suez Canal', 'Erie Canal'], 'C'),
    question('Which country is home to Mount Fuji?', ['China', 'South Korea', 'Nepal', 'Japan'], 'D'),
    question('Which European capital sits on the Danube and was once two cities, Buda and Pest?', ['Budapest', 'Vienna', 'Bratislava', 'Belgrade'], 'A'),
    question('Which country is home to the city of Mumbai?', ['India', 'China', 'United States', 'Indonesia'], 'A'),
    question('Which ocean lies between Africa and Australia?', ['Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean'], 'B'),
    question('What is the capital of Argentina?', ['Santiago', 'Lima', 'Buenos Aires', 'Montevideo'], 'C'),
    question('Which African country completely surrounds Lesotho?', ['Botswana', 'Zimbabwe', 'Mozambique', 'South Africa'], 'D'),
    question('Which sea is bordered by Ukraine, Turkey, Bulgaria, Romania, Georgia, and Russia?', ['Black Sea', 'Baltic Sea', 'Caspian Sea', 'North Sea'], 'A'),
    question('Which country contains the region of Transylvania?', ['Romania', 'Hungary', 'Serbia', 'Slovakia'], 'A'),
  ],
  5,
);
