import { makePreset, question } from '../builders';

export default makePreset(
  'pokemon',
  'Pokemon',
  'Creatures',
  'Types, regions, evolutions, battles, and trainer lore.',
  [
    question('Which Pokemon is known as the mascot of the franchise?', ['Pikachu', 'Eevee', 'Charizard', 'Mewtwo'], 'A'),
    question('What type is Squirtle?', ['Fire', 'Water', 'Grass', 'Electric'], 'B'),
    question('Which Pokemon evolves into Raichu?', ['Pichu', 'Jolteon', 'Pikachu', 'Dedenne'], 'C'),
    question('Which region is featured in Pokemon Red and Blue?', ['Johto', 'Hoenn', 'Sinnoh', 'Kanto'], 'D'),
    question('What item is normally used to catch wild Pokemon?', ['Poke Ball', 'Potion', 'Rare Candy', 'Escape Rope'], 'A'),
    question('Which Pokemon is number 001 in the National Pokedex?', ['Charmander', 'Bulbasaur', 'Squirtle', 'Pikachu'], 'B'),
    question('Which type is super effective against Water-type Pokemon?', ['Fire', 'Steel', 'Electric', 'Ice'], 'C'),
    question('Which legendary Pokemon is associated with time in Sinnoh lore?', ['Palkia', 'Giratina', 'Arceus', 'Dialga'], 'D'),
    question('Which Pokemon evolves from Magikarp?', ['Gyarados', 'Milotic', 'Dragonite', 'Lapras'], 'A'),
    question('Which professor gives trainers their first Pokemon in Kanto?', ['Professor Oak', 'Professor Elm', 'Professor Birch', 'Professor Rowan'], 'A'),
    question('Which Pokemon can evolve into Vaporeon, Jolteon, and Flareon?', ['Ditto', 'Eevee', 'Meowth', 'Togepi'], 'B'),
    question('What is Charizard\'s typing in most mainline games?', ['Fire/Dragon', 'Dragon/Flying', 'Fire/Flying', 'Fire/Rock'], 'C'),
    question('Which villainous team appears in Pokemon Ruby and Sapphire alongside Team Magma?', ['Team Rocket', 'Team Galactic', 'Team Plasma', 'Team Aqua'], 'D'),
    question('Which Pokemon is famous for copying other Pokemon with Transform?', ['Ditto', 'Smeargle', 'Mimikyu', 'Zoroark'], 'A'),
    question('Which type has no effect on Ghost-type Pokemon?', ['Normal', 'Poison', 'Psychic', 'Bug'], 'A'),
    question('Which starter Pokemon is a Fire-type lizard from Kanto?', ['Cyndaquil', 'Charmander', 'Torchic', 'Chimchar'], 'B'),
    question('Which move always leaves the target with at least 1 HP if it hits?', ['Hyper Beam', 'Earthquake', 'False Swipe', 'Surf'], 'C'),
    question('Which Pokemon is known for sleeping and blocking paths in early games?', ['Slowpoke', 'Slaking', 'Komala', 'Snorlax'], 'D'),
    question('Which region is the setting of Pokemon Gold and Silver?', ['Johto', 'Unova', 'Kalos', 'Alola'], 'A'),
    question('Which Pokemon type is immune to Electric-type moves?', ['Ground', 'Water', 'Flying', 'Steel'], 'A'),
    question('Which device records Pokemon data for trainers?', ['Rotom Bike', 'Pokedex', 'VS Seeker', 'Town Map'], 'B'),
    question('Which Pokemon evolves into Dragonite?', ['Dratini', 'Salamence', 'Dragonair', 'Altaria'], 'C'),
    question('Which legendary birds are Articuno, Zapdos, and Moltres?', ['Johto beasts', 'Sinnoh lake trio', 'Hoenn weather trio', 'Kanto trio'], 'D'),
    question('Which Pokemon is often able to learn many moves through TMs because of its artificial origin?', ['Mewtwo', 'Onix', 'Psyduck', 'Geodude'], 'A'),
    question('Which berry-like item restores HP during battle in many games?', ['Oran Berry', 'Thunder Stone', 'Repel', 'Nugget'], 'A'),
    question('Which Pokemon type is weak to Fire, Flying, and Rock?', ['Water', 'Bug', 'Electric', 'Ghost'], 'B'),
    question('Which move is a Water-type HM in many earlier games?', ['Cut', 'Fly', 'Surf', 'Strength'], 'C'),
    question('Which Pokemon is the evolved form of Haunter when traded?', ['Misdreavus', 'Sableye', 'Banette', 'Gengar'], 'D'),
    question('Which Pokemon is known for saying its own name in the anime and traveling with Ash?', ['Pikachu', 'Piplup', 'Lucario', 'Greninja'], 'A'),
    question('Which region introduced Treecko, Torchic, and Mudkip?', ['Hoenn', 'Kanto', 'Johto', 'Sinnoh'], 'A'),
    question('Which type is super effective against Dragon-type Pokemon?', ['Electric', 'Ice', 'Fire', 'Poison'], 'B'),
    question('Which Pokemon can hatch from an Egg and evolve into Pikachu through friendship?', ['Togepi', 'Azurill', 'Pichu', 'Riolu'], 'C'),
    question('Which status condition can stop a Pokemon from moving and may wear off after a few turns?', ['Burn', 'Poison', 'Confusion', 'Sleep'], 'D'),
    question('Which Pokemon is known as the Genetic Pokemon?', ['Mewtwo', 'Mew', 'Deoxys', 'Genesect'], 'A'),
    question('Which Alola form changes Vulpix from Fire type to Ice type?', ['Alolan Vulpix', 'Galarian Vulpix', 'Paldean Vulpix', 'Hisuian Vulpix'], 'A'),
    question('Which Pokemon evolves into Lucario?', ['Ralts', 'Riolu', 'Shinx', 'Buneary'], 'B'),
    question('What type is strong against Psychic-type Pokemon?', ['Fighting', 'Poison', 'Dark', 'Ground'], 'C'),
    question('Which item can revive a fainted Pokemon with some HP?', ['Potion', 'Escape Rope', 'Antidote', 'Revive'], 'D'),
    question('Which Pokemon is the final evolution of Rowlet?', ['Decidueye', 'Dartrix', 'Toucannon', 'Talonflame'], 'A'),
    question('Which Pokemon is known for disguising itself as Pikachu?', ['Mimikyu', 'Plusle', 'Minun', 'Morpeko'], 'A'),
  ],
  7,
);
