import { makePreset, question } from '../builders';

export default makePreset(
  'pop-culture',
  'Pop Culture',
  'Entertainment',
  'Movies, music, TV, icons, and fandom staples.',
  [
    question('Who is known as the King of Pop?', ['Prince', 'Michael Jackson', 'Elvis Presley', 'Bruno Mars'], 'B'),
    question('Which movie features the line "May the Force be with you"?', ['Star Wars', 'Avatar', 'The Matrix', 'Dune'], 'A'),
    question('Which superhero is also known as the Dark Knight?', ['Iron Man', 'Batman', 'Superman', 'Spider-Man'], 'B'),
    question('What fictional school does Harry Potter attend?', ['Hogwarts', 'Beauxbatons', 'Ilvermorny', 'Durmstrang'], 'A'),
    question('Which TV show features the coffee shop Central Perk?', ['Friends', 'Seinfeld', 'The Office', 'How I Met Your Mother'], 'A'),
    question('Which singer released the album 1989?', ['Adele', 'Taylor Swift', 'Billie Eilish', 'Rihanna'], 'B'),
    question('Which franchise features lightsabers?', ['Star Trek', 'Star Wars', 'Blade Runner', 'Alien'], 'B'),
    question('Who played Jack in Titanic?', ['Brad Pitt', 'Leonardo DiCaprio', 'Tom Cruise', 'Matt Damon'], 'B'),
    question('Which animated film features Elsa?', ['Moana', 'Frozen', 'Brave', 'Tangled'], 'B'),
    question('What is the name of the toy cowboy in Toy Story?', ['Buzz', 'Woody', 'Andy', 'Rex'], 'B'),
    question('Which streaming series features Hawkins, Indiana?', ['Stranger Things', 'Wednesday', 'Dark', 'Loki'], 'A'),
    question('Which band released Bohemian Rhapsody?', ['Queen', 'The Beatles', 'ABBA', 'Nirvana'], 'A'),
    question('Which Marvel hero uses a hammer called Mjolnir?', ['Thor', 'Hulk', 'Hawkeye', 'Vision'], 'A'),
    question('What color are the Simpsons usually drawn?', ['Blue', 'Yellow', 'Green', 'Pink'], 'B'),
    question('Which movie franchise features Dominic Toretto?', ['John Wick', 'Fast & Furious', 'Mission: Impossible', 'Transformers'], 'B'),
    question('Which artist is known for the song Bad Guy?', ['Lorde', 'Billie Eilish', 'Dua Lipa', 'Olivia Rodrigo'], 'B'),
    question('Which fantasy series features the One Ring?', ['Harry Potter', 'The Lord of the Rings', 'Narnia', 'Percy Jackson'], 'B'),
    question('Which character lives in a pineapple under the sea?', ['Patrick', 'SpongeBob', 'Squidward', 'Plankton'], 'B'),
    question('Which film features the song My Heart Will Go On?', ['Titanic', 'Moulin Rouge!', 'La La Land', 'Frozen'], 'A'),
    question('Which show is set at Dunder Mifflin?', ['Parks and Recreation', 'The Office', 'Brooklyn Nine-Nine', 'Community'], 'B'),
    question('Which actor played Iron Man in the Marvel Cinematic Universe?', ['Chris Evans', 'Robert Downey Jr.', 'Mark Ruffalo', 'Chris Hemsworth'], 'B'),
    question('Which fantasy TV series is based on A Song of Ice and Fire?', ['The Witcher', 'The Wheel of Time', 'Game of Thrones', 'Shadow and Bone'], 'C'),
    question('Which artist released the album Thriller?', ['Prince', 'Madonna', 'Stevie Wonder', 'Michael Jackson'], 'D'),
    question('Which movie features a DeLorean time machine?', ['Back to the Future', 'Ghostbusters', 'The Goonies', 'Blade Runner'], 'A'),
    question('Which sitcom follows a study group at Greendale Community College?', ['Community', 'New Girl', '30 Rock', 'Modern Family'], 'A'),
    question('Which singer is known as Queen Bey?', ['Rihanna', 'Beyonce', 'Ariana Grande', 'Lady Gaga'], 'B'),
    question('Which movie franchise includes the character Jack Sparrow?', ['Indiana Jones', 'The Mummy', 'Pirates of the Caribbean', 'National Treasure'], 'C'),
    question('Which animated series features Aang as the Avatar?', ['Dragon Ball Z', 'Naruto', 'One Piece', 'Avatar: The Last Airbender'], 'D'),
    question('Which band is associated with the album Abbey Road?', ['The Beatles', 'The Rolling Stones', 'Pink Floyd', 'Led Zeppelin'], 'A'),
    question('Which horror film features the masked killer Ghostface?', ['Scream', 'Halloween', 'Friday the 13th', 'A Nightmare on Elm Street'], 'A'),
    question('Which character says "I am your father" in The Empire Strikes Back?', ['Yoda', 'Darth Vader', 'Obi-Wan Kenobi', 'Emperor Palpatine'], 'B'),
    question('Which TV series follows Walter White and Jesse Pinkman?', ['Better Call Saul', 'Ozark', 'Breaking Bad', 'Fargo'], 'C'),
    question('Which fictional detective lives at 221B Baker Street?', ['Hercule Poirot', 'Philip Marlowe', 'Sam Spade', 'Sherlock Holmes'], 'D'),
    question('Which musical features the song Defying Gravity?', ['Wicked', 'Hamilton', 'Cats', 'The Lion King'], 'A'),
    question('Which movie introduced the character Shrek?', ['Shrek', 'Ice Age', 'Madagascar', 'Monsters, Inc.'], 'A'),
    question('Which pop star is known for the album The Fame?', ['Katy Perry', 'Lady Gaga', 'Kesha', 'Miley Cyrus'], 'B'),
    question('Which film franchise centers on Katniss Everdeen?', ['Divergent', 'Twilight', 'The Hunger Games', 'Maze Runner'], 'C'),
    question('Which streaming show follows the Bridgerton family in Regency-era London?', ['The Crown', 'Downton Abbey', 'Outlander', 'Bridgerton'], 'D'),
    question('Which animated movie features the character Lightning McQueen?', ['Cars', 'Planes', 'Toy Story', 'WALL-E'], 'A'),
    question('Which rapper released the album The Marshall Mathers LP?', ['Eminem', 'Drake', 'Jay-Z', 'Kanye West'], 'A'),
  ],
  4,
);
