import { makePreset, question } from '../builders';

export default makePreset(
  'science',
  'Science',
  'Discovery',
  'Space, biology, chemistry, physics, and Earth science.',
  [
    question('What planet is known as the Red Planet?', ['Venus', 'Mars', 'Jupiter', 'Mercury'], 'B'),
    question('What gas do plants absorb during photosynthesis?', ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Helium'], 'C'),
    question('What is H2O commonly known as?', ['Salt', 'Water', 'Hydrogen peroxide', 'Ozone'], 'B'),
    question('What force keeps planets in orbit around the Sun?', ['Magnetism', 'Gravity', 'Friction', 'Tension'], 'B'),
    question('Which organ pumps blood through the body?', ['Liver', 'Heart', 'Lung', 'Kidney'], 'B'),
    question('What particle has a negative electric charge?', ['Proton', 'Neutron', 'Electron', 'Photon'], 'C'),
    question('What is the boiling point of water at sea level?', ['50 C', '75 C', '100 C', '150 C'], 'C'),
    question('Which layer protects Earth from much ultraviolet radiation?', ['Troposphere', 'Ozone layer', 'Lithosphere', 'Core'], 'B'),
    question('What is the chemical symbol for gold?', ['Go', 'Gd', 'Au', 'Ag'], 'C'),
    question('Which scientist proposed the theory of general relativity?', ['Isaac Newton', 'Albert Einstein', 'Marie Curie', 'Niels Bohr'], 'B'),
    question('What is the basic unit of life?', ['Atom', 'Cell', 'Organ', 'Tissue'], 'B'),
    question('Which blood cells help fight infection?', ['Red blood cells', 'White blood cells', 'Platelets', 'Plasma'], 'B'),
    question('What type of energy does a moving object have?', ['Thermal', 'Kinetic', 'Chemical', 'Elastic'], 'B'),
    question('Which planet has the most prominent ring system?', ['Mars', 'Saturn', 'Earth', 'Venus'], 'B'),
    question('What scale measures earthquake magnitude?', ['Beaufort', 'Richter', 'Celsius', 'pH'], 'B'),
    question('Which vitamin is produced when skin is exposed to sunlight?', ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'], 'C'),
    question('What is the center of an atom called?', ['Shell', 'Nucleus', 'Membrane', 'Core sample'], 'B'),
    question('What does DNA store?', ['Genetic information', 'Oxygen', 'Heat', 'Water'], 'A'),
    question('Which process turns a liquid into gas?', ['Freezing', 'Condensation', 'Evaporation', 'Deposition'], 'C'),
    question('Which animal group includes frogs and salamanders?', ['Reptiles', 'Amphibians', 'Mammals', 'Birds'], 'B'),
    question('What is the powerhouse of the cell?', ['Ribosome', 'Mitochondrion', 'Nucleus', 'Golgi apparatus'], 'B'),
    question('Which gas makes up most of Earth\'s atmosphere?', ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon'], 'C'),
    question('What is the pH of a neutral solution at room temperature?', ['1', '10', '14', '7'], 'D'),
    question('Which scientist is famous for laws of motion and universal gravitation?', ['Isaac Newton', 'Charles Darwin', 'Ada Lovelace', 'Rosalind Franklin'], 'A'),
    question('What type of bond involves sharing electron pairs?', ['Covalent bond', 'Ionic bond', 'Metallic bond', 'Hydrogen bond'], 'A'),
    question('Which planet is the largest in our solar system?', ['Saturn', 'Jupiter', 'Neptune', 'Earth'], 'B'),
    question('What instrument is used to measure atmospheric pressure?', ['Thermometer', 'Anemometer', 'Barometer', 'Seismometer'], 'C'),
    question('Which subatomic particle has no electric charge?', ['Proton', 'Electron', 'Muon', 'Neutron'], 'D'),
    question('What is the process by which plants release water vapor from leaves?', ['Transpiration', 'Fermentation', 'Osmosis', 'Diffusion'], 'A'),
    question('Which branch of science studies fossils?', ['Paleontology', 'Meteorology', 'Astronomy', 'Ecology'], 'A'),
    question('What is the nearest star to Earth?', ['Proxima Centauri', 'The Sun', 'Sirius', 'Vega'], 'B'),
    question('Which organelle contains most of a cell\'s DNA?', ['Lysosome', 'Vacuole', 'Nucleus', 'Chloroplast'], 'C'),
    question('What is the chemical symbol for sodium?', ['So', 'Sd', 'Sn', 'Na'], 'D'),
    question('Which wave type can travel through the vacuum of space?', ['Electromagnetic', 'Sound', 'Seismic S-wave', 'Water wave'], 'A'),
    question('What is the study of heredity called?', ['Genetics', 'Geology', 'Anatomy', 'Botany'], 'A'),
    question('Which part of the electromagnetic spectrum has the shortest wavelength?', ['Radio waves', 'Gamma rays', 'Microwaves', 'Infrared'], 'B'),
    question('What do enzymes mainly do in living organisms?', ['Store memories', 'Carry oxygen', 'Speed up chemical reactions', 'Build bones'], 'C'),
    question('Which law says energy cannot be created or destroyed in an isolated system?', ['Boyle\'s law', 'Ohm\'s law', 'Hooke\'s law', 'Conservation of energy'], 'D'),
    question('What is Earth\'s outermost rigid layer called?', ['Lithosphere', 'Mesosphere', 'Outer core', 'Asthenosphere'], 'A'),
    question('Which molecule carries amino acids to the ribosome during protein synthesis?', ['tRNA', 'DNA', 'mRNA polymerase', 'ATP'], 'A'),
  ],
  3,
);
