import { makePreset, question } from '../builders';

export default makePreset(
  'technology',
  'Technology',
  'Digital',
  'Computers, web basics, devices, and modern tech.',
  [
    question('What does CPU stand for?', ['Central Processing Unit', 'Computer Power Utility', 'Core Program Unit', 'Central Pixel Unit'], 'A'),
    question('Which language is primarily used for styling web pages?', ['HTML', 'CSS', 'SQL', 'Python'], 'B'),
    question('What does URL stand for?', ['Uniform Resource Locator', 'Universal Runtime Link', 'User Request Label', 'Unified Router List'], 'A'),
    question('Which company created the iPhone?', ['Google', 'Apple', 'Samsung', 'Nokia'], 'B'),
    question('What does RAM store?', ['Temporary working data', 'Printed pages', 'Battery charge', 'Screen brightness'], 'A'),
    question('Which protocol is commonly used for secure websites?', ['FTP', 'HTTP', 'HTTPS', 'SMTP'], 'C'),
    question('What is Git used for?', ['Image editing', 'Version control', 'Video streaming', 'Password cracking'], 'B'),
    question('Which database language is used for queries?', ['CSS', 'SQL', 'SVG', 'Bash'], 'B'),
    question('What does AI stand for?', ['Automated Input', 'Artificial Intelligence', 'Analog Interface', 'Applied Internet'], 'B'),
    question('Which file extension often contains JavaScript?', ['.jpg', '.js', '.mp3', '.zip'], 'B'),
    question('What does a browser do?', ['Runs websites', 'Prints circuits', 'Charges phones', 'Stores furniture'], 'A'),
    question('Which company developed Android?', ['Microsoft', 'Google', 'Sony', 'IBM'], 'B'),
    question('What is two-factor authentication used for?', ['Faster charging', 'Extra login security', 'Better graphics', 'File compression'], 'B'),
    question('Which device routes internet traffic in a home network?', ['Router', 'Monitor', 'Keyboard', 'Printer'], 'A'),
    question('What does HTML define?', ['Page structure', 'Database indexes', 'Battery health', 'Image resolution'], 'A'),
    question('Which cloud term means renting computing resources over the internet?', ['Cloud computing', 'Packet painting', 'Cable casting', 'Data drying'], 'A'),
    question('What is phishing?', ['A cyber scam', 'A graphics setting', 'A keyboard shortcut', 'A storage format'], 'A'),
    question('Which unit is larger?', ['Kilobyte', 'Megabyte', 'Byte', 'Bit'], 'B'),
    question('What is an API?', ['Application Programming Interface', 'Automatic Pixel Importer', 'Advanced Power Input', 'Audio Processing Icon'], 'A'),
    question('Which tool is used to inspect web page elements in browsers?', ['Developer tools', 'Paint bucket', 'Disk cleanup', 'Task scheduler'], 'A'),
    question('What does DNS help translate?', ['Images to icons', 'Domain names to IP addresses', 'Passwords to tokens', 'Audio to text'], 'B'),
    question('Which data structure uses first-in, first-out ordering?', ['Stack', 'Tree', 'Queue', 'Graph'], 'C'),
    question('Which protocol is commonly used to send email between mail servers?', ['SSH', 'NTP', 'DHCP', 'SMTP'], 'D'),
    question('What does SSD stand for?', ['Solid State Drive', 'System Storage Dock', 'Secure Signal Device', 'Software Service Driver'], 'A'),
    question('Which binary digit values are used in basic digital computing?', ['0 and 1', '1 and 2', 'A and B', 'X and Y'], 'A'),
    question('What does HTTP mainly transfer?', ['Electric current', 'Hypertext and web resources', 'Satellite coordinates', 'Printed documents'], 'B'),
    question('Which language runs directly in most web browsers?', ['C++', 'Rust', 'JavaScript', 'Swift'], 'C'),
    question('What is encryption used for?', ['Deleting old files', 'Cooling processors', 'Increasing screen size', 'Protecting readable data by encoding it'], 'D'),
    question('Which component renders images to a display?', ['GPU', 'PSU', 'SSD', 'NIC'], 'A'),
    question('What does open-source software usually provide access to?', ['Source code', 'Private passwords', 'Secret hardware', 'Paid-only updates'], 'A'),
    question('Which network device assigns local IP addresses in many home networks?', ['Speaker', 'Router', 'Scanner', 'Projector'], 'B'),
    question('Which command-line tool is commonly used to clone Git repositories?', ['git copy', 'repo take', 'git clone', 'branch pull'], 'C'),
    question('What is a cookie in web browsing?', ['A compressed image', 'A firewall rule', 'A screen pixel', 'Small site data stored by the browser'], 'D'),
    question('Which database type stores rows and columns in tables?', ['Relational database', 'Vector database only', 'Flat image store', 'Packet switch'], 'A'),
    question('What does MFA stand for in account security?', ['Multi-factor authentication', 'Main file archive', 'Managed firewall adapter', 'Memory fault alert'], 'A'),
    question('Which file format is commonly used for structured data interchange on the web?', ['MP3', 'JSON', 'JPEG', 'EXE'], 'B'),
    question('What is latency in networking?', ['Maximum hard drive size', 'Screen brightness level', 'Delay before data transfer response', 'Battery health score'], 'C'),
    question('Which cloud model provides virtual machines and storage infrastructure?', ['JPEG', 'BIOS', 'OLED', 'IaaS'], 'D'),
    question('What does a compiler do?', ['Translates source code into another form', 'Charges a laptop', 'Routes Wi-Fi traffic', 'Cleans a monitor'], 'A'),
    question('Which technology lets devices communicate over short distances without wires?', ['Bluetooth', 'SATA', 'HDMI', 'Ethernet'], 'A'),
  ],
  6,
);
